### PR TITLE
Solved Day 9

### PR DESCRIPTION
**Pull request by O-Abdelaziz**

### CODE REVIEW

**Comment by Haidyasser** [comment]
Great work.
but think about the worst scenario. what if the vector is empty?

**Comment by O-Abdelaziz** [comment]
> Great work. but think about the worst scenario. what if the vector is empty?

_The loop for (int i = 0; i < v.size() - 1; i++) would not execute and the function will return false, showing that no duplicates exist, but we might add a function to verify if the vector is empty, as seen below._

**if (v.empty()) {
        return false;
    }**

**Comment by Haidyasser** [comment]
I know your logic is correct. the thing is that size() function does not return an integer value. it returns a size_t type which is more like an unsigned int type. so the subtraction of 1 from 0 will not be a -1, the value will be converted into a very large number which will cause a runtime error.

**Comment by O-Abdelaziz** [comment]
Great, 

> I know your logic is correct. the thing is that size() function does not return an integer value. it returns a size_t type which is more like an unsigned int type. so the subtraction of 1 from 0 will not be a -1, the value will be converted into a very large number which will cause a runtime error.

Really appreciate the information!

**Pull request merged**
